### ISSUE TITLE
[Component] Drawer

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#1580]

**Comment by soykje** [comment]
An experimental develpment have been made: https://sparkui.vercel.app/?path=/docs/experimental-drawer--docs. For now it seems we should confirm that all expected features are in, and that this experiment is compliant with Design specs (incoming). :+1:

**Comment by Powerplex** [comment]
Final test link: https://spark-3elstmrq6-spark-team.vercel.app/?path=/docs/components-drawer--docs

**Comment by elisa-hery** [comment]
Here are my comment @Powerplex @Bibisirius : 
1) **in ZH**, 2 sections are not up-to-date with figma : 1) the first diagram is not right (F/G/H are not at the right place) 2) "sizes" section : for full screen according to figma it's `width` and not `max-width`
2) **a11y** :  for scrollable content, we cannot reach body with keyboard navigation so we cannot read the full text. But I guess it is the same problem that we had with modal ?
3) **a11y** : when i'm closing a drawer, focus always come back on the last trigger button of the list (see video below) 

https://github.com/adevinta/spark/assets/142396647/9f0eafe9-f062-4e20-849a-358bca35be05

4) **content resilience** : long titles overlap onto the cross ⬇️  Is it same problematic as for modale (see slack thread [here](https://adevinta.slack.com/archives/C056PNNGWTY/p1695996649937019))  ?  
<img src="https://github.com/adevinta/spark/assets/142396647/974e3822-324f-44e6-9425-fbad4ebd3ec8" alt="isolated" width="500"/>

5) on chrome mobile, I sometimes see a **small glitch** between lines, see following videos : 

https://github.com/adevinta/spark/assets/142396647/44cef7b0-41f1-4199-97d4-89ce8b2005fa
https://github.com/adevinta/spark/assets/142396647/a917d8d8-24fe-44d5-a1a2-942bf0b045de

Fell free to ask me if it's not clear !

**Comment by Powerplex** [comment]
_a11y : for scrollable content, we cannot reach body with keyboard navigation so we cannot read the full text. But I guess it is the same problem that we had with modal ?_ => Yes, same problem. We should discuss this topic some day together, because fixing it would introduce something worse.

_a11y : when i'm closing a drawer, focus always come back on the last trigger button of the list (see video below)_ => This is because I'm using four triggers for a single drawer. It can't guess which one triggered it unfortunately. Not a standard use-case. I could easily fix it in Storybook by making it 1 trigger = 1 drawer, but it would make the markup hard to read for developers when they click "show code". WDYT ?

**Comment by elisa-hery** [comment]
Update : 
1) @Bibisirius is updating ZH 🕐 
2) we cannot resolve this for now ✅ 
3) @Powerplex is updating Storybook so that we don't have this problem anymore 🕐 
4) same problematic as for modale. @Bibisirius : @Powerplex proposed to add a spec like "if there is a header, add a padding to `Dialog.Title`, WDYT ?
5) this problem linked to the simulator, it does not exists on mobile ✅
