### ISSUE TITLE
[Figma] adapt / improve the component Drawer to allow fluid size

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1802]
Based in [this Slack thread](https://adevinta.slack.com/archives/C05TMF11T33/p1704385972842219?thread_ts=1704368184.836659&cid=C05TMF11T33)

**Comment by Bibisirius** [comment]
- [x] Figma 
- [ ] Zeroheight spec

**Comment by Powerplex** [comment]
Can we discuss this one soon ?  If we do it, it might require adding it to Dialog to be consistant. I noticed also that most DS chose not to have a fluid size.

Right now all our sizes are already "fluid" in that when the screen get smaller, it will adapt, but not the other way around. fluid  can be weird for web for example on a drawer in left/right position, because html content naturally take as much width as they can, so a simple long paragraph in a drawer with `size="fluid"`  and `side="right"`  would result in a fullscreen drawer for example. I think that's why it's not very popular.

Also the maximum height/width of a drawer can already be customized as it is today.

**Comment by turolopezsanabria** [comment]
Yes! Let's discuss this in the next Specs Reviews session.
I'll add it as topic

**Comment by Bibisirius** [comment]
- We will add fluid size, the need from design is only for bottom and top drawers
- We might allow but discourage the use of fluid size in left and right
- We will not provide this prop in Figma for side drawers
- We decided back ago not to have Bottom sheets because
- Specific to mobile
- Performance issues
- etc

**Comment by Bibisirius** [comment]
- Update on ZH: [url](https://spark.adevinta.com/1186e1705/p/900abd-drawer/t/298123)
- Update Figma spec: [url](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=11237-18027&mode=design&t=fcI5FLrvzmIoP1yf-11)

**Comment by Bibisirius** [comment]
👍
