### ISSUE TITLE
[Component] Badge outline color

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1906]
We change the outline color by Base/surface by default 
Spec: [url](https://spark.adevinta.com/1186e1705/p/8711ec-badge/t/06fc01)

![Image](https://github.com/adevinta/spark/assets/139967199/0b5dd044-5572-4670-b507-a0343210cfc9)

**Comment by acd02** [comment]
I've used the `on-surface` token when the intent is **surface**, because otherwise we end up with something like this (see picture below),
what are your thoughts on this, @Bibisirius ?


<img width="358" alt="Screenshot 2024-02-23 at 15 56 36" src="https://github.com/adevinta/spark/assets/51230231/9680048d-af90-44fe-88e7-abba0633df9a">
<img width="350" alt="Screenshot 2024-02-23 at 15 55 28" src="https://github.com/adevinta/spark/assets/51230231/176f620c-b684-455e-90a4-de3407181fff">

**Comment by elisa-hery** [comment]
ariane link = https://spark-28xkda7bi-spark-team.vercel.app/?path=/docs/components-badge--docs

**Comment by Bibisirius** [comment]
Hi ! 
The outline badge must be` surface` by defaut 
Here's the link to the topic: [here ](https://github.com/adevinta/spark/issues/1880)

**Comment by acd02** [comment]
👋 @Bibisirius , ok, so I'll go with **B** then 👍

**Comment by Bibisirius** [comment]
Perfect!  This corresponds to the update on Figma
Thanks @acd02 🙏
