### ISSUE TITLE
[Component] - Snackbar

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#2199]
If you watch the video below, you will understand the bug. Essentially, if you slightly swipe the snackbar without swiping enough to close it, the `onClose` button fails to close the snackbar.

Additionally, the `timeout` function that should automatically close the snackbar after 5 seconds also becomes inactive.
When in this state, the only way to close the snackbar is to swipe it

![Image](https://github.com/adevinta/spark/assets/51230231/0f7479fc-e103-45f6-b49d-0ec70c256aa2)

**Comment by soykje** [comment]
@elisa-hery Ready for QA time: https://spark-ui-uhip-n4q4w74h4-sparkteams-projects.vercel.app/iframe.html?id=components-snackbar--close&viewMode=story 🙏

**Comment by elisa-hery** [comment]
@soykje I tested all [these cases](https://docs.google.com/spreadsheets/d/1plmBTjbBxT7SyDgrxlRjYHvlS9fYjJVRlGwbpet-HoM/edit?gid=1435862231#gid=1435862231) on safari web / safari mobile / chrome web : it's all good, this bug is fixed ✅

Nevertheless it made me notice 2 things : 

1. on **safari** (Version 17.4.1), with keyboard navigation, enter or space don't trigger action or close button (I know you cannot work on safari, but at least maybe I should show you)
2. with a long text in the action button, the button takes the whole space (and also it's not vertically aligned), and I'm not sure this is what we want : 
<img width="467" alt="Screenshot 2024-06-18 at 11 30 45" src="https://github.com/adevinta/spark/assets/142396647/046d2fbc-ec53-44a1-b0b4-2368b262b835">

maybe we can talk about this !

**Comment by elisa-hery** [comment]
1. we created a new task for this --> https://github.com/adevinta/spark/issues/2249 
2. @soykje fixed it ✅
