### ISSUE TITLE
[Component] - Combobox - keyboard navigation

### ISSUE THREAD

**Issue by halljus** [adevinta/spark#2414]
### Description

Not sure if this is a true feature request as much as it is a question, but should the Combobox component allow navigating to the clear and disclosure buttons via the keyboard? It doesn't seem to as of version 5.3.7.

Additionally, it doesn't appear that you can use left arrow to focus a selected item chip if there is only one selection (like you can when there are multiple) - is that the intended behavior or a bug?

### Problem Statement/Justification

As a keyboard user, I expected to be able to navigate to the clear and disclosure buttons within the Combobox, but I wasn't able to find a way to do so. I'd also expect to be able to navigate to the selected item chip when there is only one selection (like you can when there are multiple items selected), but this is a much lower priority.

### Proposed Solution or API

Enable keyboard navigation to the clear and disclosure buttons (via right arrow?), and possibly to a single selected item chip.

### Additional Information

I should mention that the disclosure button does appear to have focus-visible styles, which made me think the intent was there (I just couldn't find a way to focus it). The clear button does not have these styles, though.

**Comment by Powerplex** [comment]
Thanks for asking and caring about a11y.

This is actually a desired feature and this approach is shared by some design systems.

## Regarding the clear button

This is to copy how a native search input behaves. A native HTML `search` input (`<input type="search"`)  also do not allow to reach the clear button with keyboard. This is because:
- The strategy is to **limit how many times a user must press Tab to traverse the page**. 
- The user CAN clear with the keyboard already (using Delete/BackSpace/Ctrl + A, etc). Only mouse users can't delete using only the mouse and this extra button is there for them to provide .
- Using the "right arrow" as you suggest would not be obvious to keyboard users as it's not a common pattern (visually impaired people will not be able to guess that there is a clear button to the right of the input)


## Regarding the disclosure button

- The strategy is to **limit how many times a user must press Tab to traverse the page**. 
- The user can press `Arrow down` to open the menu while focused in the input. This is thanks to the `combobox` [role and pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)

## Selected item chip in single selection mode

> I'd also expect to be able to navigate to the selected item chip when there is only one selection (like you can when there are multiple items selected), but this is a much lower priority.

`Combobox.SelectedItems` is reserved for multiple selection mode only. This is because in single selection mode, the input of the combobox reflects the label of the selected item, so you can then edit it directly (for example if your combobox has `allowCustomValue` passed to it, you can select an item then modify it's value. It can be usefull when building a search input with the combobox).

To note: You can reach each chip individually using left/right arrows in multiple selection mode, and delete them using Delete/Backspace, but as it is not a standardized approach to combobox and is not part of the combobox aria pattern (a visually impaired person can also not guess that the chips exists), the main way to unselect items with keyboard remains by accessing them from the menu.

**Comment by halljus** [comment]
Thank you for the response, that all makes sense! However, I think there may still be a bug with regards to selecting (and thus, deleting) the last remaining selection in multi-select mode. I'll open a new issue for that specific problem.
