### ISSUE TITLE
[Exploration] Figma: Find a solution for UI Kits in Figma to allow multi-theming (tokens approach)

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#49]

**Comment by solygambas** [comment]
We'll begin by the buttons.

**Comment by solygambas** [comment]
The PoC seems now good enough to be fully integrated with the designers' workflow.

Here are the requirements to re-structure our Figma kits:
- to have switchable color keys, we need a lib per theme (light, dark, private, pro, etc.).
- each Figma style has an ID. We need a plugin to sync color tokens with their IDs. We will store this in a JSON file available on GitHub.
- on every theme update, we need to push to GitHub via the plugin and publish the Figma library update.
- in a Figma file, the plugin matches color keys from one theme to another. It keeps the link to the corresponding Figma library.

Next steps:
- testing with an actual example.
- defining if there is a free plugin to do that rather than the paid version of Tokens Studio for Figma.

https://user-images.githubusercontent.com/51904909/231759013-856650d1-ce21-42d7-a1b2-b051a7a4ebb4.mov

**Comment by turolopezsanabria** [comment]
We are not ready yet to adopt this, we need a Team agreement 1st.
Please don't update any UI Kit until we have a complete understanding of the scope and posssible usage, with a scalable strategy that will cover all.

**Comment by turolopezsanabria** [comment]
PLugin published by @solygambas 
check our Slack channel conversation here:
https://adevinta.slack.com/archives/C04R5SR8GCA

**Comment by turolopezsanabria** [comment]
I'll re-poen this ticket, we don't have an agreement yet
