### ISSUE TITLE
Button Group

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#542]
### Description

Add ButtonGroup component so props could be shared across all buttons.

### Problem Statement/Justification

If we want to group two buttons with the same size right now the users will need to repeat the props (e.g. `size`) for both of them.

### Proposed Solution or API

```jsx
<ButtonGroup className="flex gap-md" size="sm" variant="outline">
  <Button>Save</Button>
  <IconButton aria-label='Add to friends' icon={<AddIcon />} />
</ButtonGroup>
```

**Comment by Powerplex** [comment]
1. ButtonGroup would also have visual implications ? Like grouping buttons together in a bar ? Like here ? [boostrap ButtonGroup](https://getbootstrap.com/docs/4.3/components/button-group/) Or is it mostly to share props on multiple button ?
2. What happens if I have `intent="neutral"` on the group, but `intent="success"` on one of the children buttons ? I think it should still be possible wdyt ?
