### ISSUE TITLE
Implement MA colors in Spark Tokens for Figma

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#820]
We need to include Milanuncios themes in the Figma Tokens plugin.

**Comment by solygambas** [comment]
- Both themes are validated, the dark theme doesn't have states yet. Lucia needs Diego's help to finish this.
- Lucia will ask her team if the new themes can be published inside the library. Right now, the theme switching doesn't work since the Figma references to the new color styles haven't been published.

**Comment by solygambas** [comment]
Merged
